### ISSUE TITLE
Is it possible to join the server with Minecraft client?

### ISSUE THREAD

**Issue by Yardanico** [SulfurCrafted/Sulfur#2]
If so, what version of Minecraft do I need?

**Comment by daniktheboss** [comment]
It's a project! Not running yet

**Comment by TiberiumPY** [comment]
But if it will be running, please check PyPy [for](pypy.org) speed! If your project uses Twisted and Pure Python, you can get really got speed boost. PyPy - alternative Python interpreter with Just-In-Time compiler!
PyPy is compatible with the most of Python 2 packages (it has good C API support, but C extensions usually work slower, than in CPython)
